Added More unit tests to the Service and Facade Layer. (#6)
* Adding just one unit test took all day. Damn. This unit test is still failing. But this is failing because Apparently MapStruct is not working in this project!!!!!

* Replaced Mapstruct with JMapper. Hopefully this is much better to use.

* Deleted the Mappers related to MapStruct as these as not valid anymore. There will be build problems which needs to be fixed next.

* Added a TODO about less Seralization/Deseralization of data.

* Unit test Added for one of the TicketFacade delete methods.

* Added another unit test for false case for delete in the TIcketFacadeTest.

* Added another unit test for Error case to the delete method.

* Added Powermock and added a unit test to a method in createANewTicket.

* Added another unit test. This says that i have not have any exception handling in the create method of service. Which is actually lousy coding if you ask me.

* Added a unit test to verify catching of Json Processing Exception. Updated the mockito version.

* Added another unit test for the updateService.

* Added another unit test for the ticketFindAndUpdate in the TicketService.

* Added one more unit test. But all this testing but this still has
Exception in thread "main" java.lang.NoSuchMethodError: 'org.mockito.MockitoFramework org.mockito.Mockito.framework()'

* Added another unit test to the TicketService.

* Added another unit test for JsonProcessingException.

* Added unit tests to TicketService Delete method.

* Added the correct version of powermock and let powermock get the version of the mockito that it wants for itself. All tests are working now and all tests are passing.

Co-authored-by: Sunil KS <sunilks.kavali@gmail.com>